### ISSUE TITLE
Add DOIs to existing publications

### ISSUE THREAD

**Issue by brycefrank** [allometric/models#14]
`RefManager::BibEntry` allows for a `doi` field. However, many publications are missing this information. This would greatly increase the quality and robustness of the publication files.

Here is an example. `hibbs_2007.R` currently has this publication, with no DOI field defined

https://github.com/allometric/models/blob/4fe0ac4037aa7a61a634746acc4c3fad97b80062/publications/f_j/hibbs_2007.R#L1-L21

but [it is clear ](https://academic.oup.com/wjaf/article/22/1/61/4718034) that a DOI is available. Adding the DOI is as simple as adding `doi = "https://doi.org/10.1093/wjaf/22.1.61"` to the `BibEntry` call. More concretely:

```{r}
 hibbs_2007 <- Publication( 
   citation = RefManageR::BibEntry( 
     bibtype = "article", 
     key = "hibbs_2011", 
     title = "Stem taper and volume of managed red alder", 
     author = "Hibbs, David and Bluhm, Andrew and Garber, Sean", 
     journal = "Western Journal of Applied Forestry", 
     volume = 22, 
     number = 1, 
     pages = "61--66", 
     year = 2007, 
     publisher = "Oxford University Press",
     doi = "https://doi.org/10.1093/wjaf/22.1.61"
   ), 
   descriptors = list( 
     country = c("US", "CA"), 
     region = c("US-OR", "US-WA", "CA-BC"), 
     family = "Betulaceae", 
     genus = "Alnus", 
     species = "rubra" 
   ) 
 ) 
```

You are welcome to make a pull requests to add these. People who are unfamiliar with git are free to provide a table (e.g., a csv file) with the following information instead

```
pub_id       doi
hibbs_2007   https://doi.org/10.1093/wjaf/22.1.61
```

for each publication that has a DOI available. It is likely the case that most publications do not have a DOI, due to the age of many of the publications, and because many of the publications are from non-peer reviewed sources. So, the total number of DOI updates will not be large.

**Comment by boenomarcus** [comment]
Hi Bryce! I updated the DOI field for some of the publications. Unfortunately, several do not have a DOI as you mentioned above.

All changes were made via a pull request (See PR https://github.com/allometric/models/pull/15)

ps: For the `curtis_1974` publication (https://academic.oup.com/forestscience/article-abstract/20/4/307/4675530?redirectedFrom=fulltext) the DOI seems to be invalid for some reason. I did not create a DOI field for this one for the moment.
