### ISSUE TITLE
Rolim & Piotto 2018

### ISSUE THREAD

**Issue by HawthorneBeyer** [allometric/models#37]
**Provide a citation of the publication you want us to add.**
```
@book{book,
author = {Rolim, Samir and Piotto, Daniel},
year = {2018},
month = {06},
pages = {},
title = {Silvicultura e Tecnologia de Espécies da Mata Atlântica},
isbn = {978-85-62805-90-5}
}
```

The report in Portuguese is available here: 
https://www.researchgate.net/publication/326262183_Silvicultura_e_Tecnologia_de_Especies_da_Mata_Atlantica
I have the version in English that I will try to attach here. If that fails (it is 23MB), I have documented where the equations are below, so you may not need the English version. However, the page numbers may be slightly off in the Portuguese version, but probably not by more than a page or so.

[Simbiosys_Silviculture2019_LowRes.pdf](https://github.com/allometric/models/files/13372055/Simbiosys_Silviculture2019_LowRes.pdf)

**Describe where the models are in the report.**
For all model equations see p23 Table 1
For top-ranked model parameters:
Hypsometry (total height): Naslund model, p24 Table 2. Also here:

```
hypsometry_rolim <- function(d){
	return((d / (0.1749 * d + 1.6080))^2)
}
```

Hyposmetry (stem height): Logistic model, p24 Table 2

Volumetric model: Shumacher-Hall p25 Table 3 (see equation form in bold just above Table 3 caption)

AGB model: "Model 5" in Table 4, p26 (see equation form in bold just above Table 4, on p25) - also here:

```
allometry_rolim <- function(d, h, rho){
	return(0.1009 * (d^2.2472) * (h^0.4333) * (rho^0.7865))
}
```

Species-specific growth models (n=35, p35 Table 2) - provided below

**Additional context**
This is an incredible collection of data-driven forest models for tropical species in Brazil. (I have no connection to the authors). 

Congrats and appreciation for your continued efforts in maintaining this valuable R package.

I have coded up the growth models in a list in R in case this saves you time, and provide an R vector of the species names in Table 2 p35:

```
gm.spp <- c("Amburana cearensis", "Aspidosperma pyricollum", "Astronium concinnum", "Astronium graveolens", "Barnebydendron riedelii", "Bowdichia virgilioides", "Cariniana legalis", "Centrolobium tomentosum", "Clarisia racemosa", "Copaifera langsdorffii", "Cordia trichotoma", "Dalbergia nigra", "Goniorrhachis marginata", "Handroanthus serratifolius", "Hymenaea courbaril var. stilbocarpa", "Joannesia princeps", "Lecythis pisonis", "Libidibia ferrea var. parvifolia", "Manilkara longifolia", "Moldenhawera papillanthera", "Myracrodruon urundeuva", "Pachira endecaphylla", "Paratecoma peroba", "Parkia pendula", "Paubrasilia echinata", "Pterocarpus rohrii", "Pterygota brasiliensis", "Senegalia polyphylla", "Simarouba amara", "Spondias venulosa", "Tachigali vulgaris", "Terminalia mameluco", "Vatairea heteroptera", "Vataireopsis araroba", "Zeyheria tuberculosa")
```

```
# growth models:
gm <- list()
gm[[1]] <- function(t){return(26.11*((1+344.74*exp(-2.32*log(t)))^(-1)))}
gm[[2]] <- function(t){return(53.88*(1-exp(-0.0348*(t^0.7192))))}
gm[[3]] <- function(t){return(23.66*exp(-3.99*(t^-0.8775)))}
gm[[4]] <- function(t){return(39.24*exp(-1.81*exp(-0.03925*t)))}
gm[[5]] <- function(t){return(47.11*exp(-4.2*t^-0.5434))}
gm[[6]] <- function(t){return(83.54*((1+42.02*exp(-0.8551*log(t)))^-1))}
gm[[7]] <- function(t){return(46.4*exp(-11.38*t^-0.9855))}
gm[[8]] <- function(t){return(46.43*exp(-8.3*t^-0.7437))}
gm[[9]] <- function(t){return(36.23*exp(-4.92*exp(-0.1038*t)))}
gm[[10]] <- function(t){return(76.46*(1+190.22*exp(-1.2478*log(t)))^-1)}
gm[[11]] <- function(t){return(41.27*exp(-2.15*exp(-0.0484*t)))}
gm[[12]] <- function(t){return(61.47*exp(-3.92*t^-0.4838))}
gm[[13]] <- function(t){return(49.36*exp(-5.15*t^-0.5634))}
gm[[14]] <- function(t){return(49.86*exp(-4.66*(t^-0.5405)))}
gm[[15]] <- function(t){return(47.67*exp(-4.08*t^-0.5847))}
gm[[16]] <- function(t){return(44.59*exp(-2.32*t^-0.3574))}
gm[[17]] <- function(t){return(60.82*exp(-4.774*t^-0.4848))}
gm[[18]] <- function(t){return(30.9*exp(-4.97*t^-0.7867))}
gm[[19]] <- function(t){return(25.25*exp(-9.59*t^-1.0455))}
gm[[20]] <- function(t){return(73.09*(1+104.6*exp(-1.059*log(t)))^-1)}
gm[[21]] <- function(t){return(60.42*(1+20.075*exp(-0.9038*log(t)))^-1)}
gm[[22]] <- function(t){return(29.124*(1-exp(-0.0413*t^1.3736)))}
gm[[23]] <- function(t){return(71.15*exp(-3.8343*t^-0.3558))}
gm[[24]] <- function(t){return(70.98*exp(-4.61*t^-0.5052))}
gm[[25]] <- function(t){return(40.69*exp(-6.03*t^-0.6845))}
gm[[26]] <- function(t){return(81.48*exp(-4.48*t^-0.4487))}
gm[[27]] <- function(t){return(89.77*(1+44.28*exp(-0.9057*log(t)))^-1)}
gm[[28]] <- function(t){return(77.54*exp(-3.935*t^-0.344))}
gm[[29]] <- function(t){return(43.98*exp(-2.34*exp(-0.0587*t)))}
gm[[30]] <- function(t){return(82.59*exp(-2.97*t^-0.4292))}
gm[[31]] <- function(t){return(90.41*exp(-5.12*t^-0.5003))}
gm[[32]] <- function(t){return(31.74*(1+168.87*exp(-1.617*log(t)))^-1)}
gm[[33]] <- function(t){return(29.25*exp(-5.62*t^-0.8561))}
gm[[34]] <- function(t){return(48.59*exp(-3.54*t^-0.4858))}
gm[[35]] <- function(t){return(37.62*(1+19.9*exp(-1.13823*log(t)))^-1)}
```

**Comment by brycefrank** [comment]
Thanks! I will take a look in the next week or so

**Comment by brycefrank** [comment]
@HawthorneBeyer 

I am drafting the models now. I will start with the smaller set of non-growth models and get to the growth models in the next week or so. Use `install_models(redownload = TRUE, ignore_cache = TRUE)` to get them into your local dataset

- I used the English paper and citation
- "Stem height" appears to refer to the length of the commercial stem, hence we use `hsm` for this and `hst` for total height.
- I added Naslund for `hst` and Logistic for `hsm` as requested
- I added Schumacher & Hall for volume
- I added Model 5 for biomass. Note that the units for wood density will be incorrectly labeled for a brief time. I need to make a small update to `allometric/allometric` to fix this. It will not affect the performance of the model.

**Comment by brycefrank** [comment]
Note to self, we should split the models out into their respective *chapters* rather than the entire book as a citation, see:

https://tex.stackexchange.com/questions/60843/how-to-cite-a-book-chapter-written-by-an-author-who-is-not-the-editor-or-author
